compose:
  - call: lcod://impl/set@1
    in:
      registrations:
        - id: "lcod://rag/jsonl/parse_objects@0.1.0"
          segment: "components/jsonl.parse_objects/compose.yaml"
        - id: "lcod://rag/array/compact@0.1.0"
          segment: "components/array.compact/compose.yaml"
        - id: "lcod://rag/array/flatten@0.1.0"
          segment: "components/array.flatten/compose.yaml"
        - id: "lcod://rag/array/pluck@0.1.0"
          segment: "components/array.pluck/compose.yaml"
        - id: "lcod://rag/registry/normalize_component@0.1.0"
          segment: "components/registry.normalize_component/compose.yaml"
        - id: "lcod://rag/registry/load_manifest_records@0.1.0"
          segment: "components/registry.load_manifest_records/compose.yaml"
        - id: "lcod://rag/registry/collect_components@0.1.0"
          segment: "components/registry.collect_components/compose.yaml"
        - id: "lcod://rag/registry/snapshot_from_components@0.1.0"
          segment: "components/registry.snapshot_from_components/compose.yaml"
        - id: "lcod://rag/registry/diff_snapshots@0.1.0"
          segment: "components/registry.diff_snapshots/compose.yaml"
        - id: "lcod://rag/registry/snapshot_read@0.1.0"
          segment: "components/registry.snapshot_read/compose.yaml"
        - id: "lcod://rag/registry/snapshot_write@0.1.0"
          segment: "components/registry.snapshot_write/compose.yaml"
        - id: "lcod://rag/registry/fetch_component_docs@0.1.0"
          segment: "components/registry.fetch_component_docs/compose.yaml"
        - id: "lcod://rag/ingest/extract_documents@0.1.0"
          segment: "components/ingest.extract_documents/compose.yaml"
        - id: "lcod://rag/ingest/chunk_documents@0.1.0"
          segment: "components/ingest.chunk_documents/compose.yaml"
        - id: "lcod://rag/ingest/embed_chunks@0.1.0"
          segment: "components/ingest.embed_chunks/compose.yaml"
        - id: "lcod://rag/ingest/ensure_collection@0.1.0"
          segment: "components/ingest.ensure_collection/compose.yaml"
        - id: "lcod://rag/ingest/upsert_chunks@0.1.0"
          segment: "components/ingest.upsert_chunks/compose.yaml"
        - id: "lcod://rag/ingest/run_pipeline@0.1.0"
          segment: "components/ingest.run_pipeline/compose.yaml"
    out:
      registrations: registrations

  - call: lcod://flow/foreach@1
    in:
      list: $.registrations
    slots:
      body:
        - call: lcod://axiom/path/join@1
          in:
            base: $.ragRoot
            segment: $slot.item.segment
          out:
            resolvedPath: path

        - call: lcod://impl/set@1
          in:
            component:
              id: $slot.item.id
              composePath: $.resolvedPath
          out:
            component: component
    collectPath: $.component
    out:
      ragComponents: results

  - call: lcod://tooling/resolver/register@1
    in:
      components: $.ragComponents
    out:
      registered: registered
      warnings: warnings
