schemaVersion = "2.0"
id = "lcod://rag/registry/register_helpers@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Register lcod-rag helper components in the resolver registry."

[palette]
category = "RAG"
icon = "mdi:account-network"
tags = ["registry", "helpers", "rag"]

[docs]
readme = "README.md"

[[io.input]]
name = "ragRoot"
summary = "Path to the lcod-rag workspace used to resolve helper composes."
required = false
schema = """
{
  "type": ["string", "null"]
}
"""

[[io.output]]
name = "helperRegistered"
summary = "Number of helper components registered."
schema = """
{
  "type": "integer"
}
"""

[[io.output]]
name = "helperWarnings"
summary = "Warnings emitted while registering the helpers."
schema = """
{
  "type": "array",
  "items": { "type": "string" }
}
"""
