compose:
  - call: lcod://tooling/script@1
    in:
      source: |
        async ({ state }, { imports }) => {
          const ensureString = (value) => (typeof value === 'string' && value.length > 0 ? value : null);
          const joinRelative = async (baseDir, segment) => {
            const resolvedBase = ensureString(baseDir) || '.';
            try {
              const joined = await imports.pathJoin({ base: resolvedBase, segment });
              return joined?.path || joined || segment;
            } catch (_) {
              return segment;
            }
          };

          const projectBase = ensureString(state.projectPath) || ensureString(state.cwd) || '.';
          const ragRootCandidate =
            ensureString(state.ragRoot) ||
            await joinRelative(projectBase, 'packages/rag');
          const isAbsolute = (value) => /^[a-zA-Z]:[\\/]/.test(value) || value?.startsWith('/');
          const resolvePath = async (candidate, fallbackBase) => {
            const value = ensureString(candidate);
            if (!value) return null;
            if (isAbsolute(value)) return value;
            const baseCandidate = ensureString(fallbackBase) || '.';
            let absoluteBase = baseCandidate;
            if (!isAbsolute(baseCandidate)) {
              try {
                const joinedBase = await imports.pathJoin({ base: process.cwd(), segment: baseCandidate });
                absoluteBase = joinedBase?.path || joinedBase || baseCandidate;
              } catch (_) {
                absoluteBase = baseCandidate;
              }
            }
            try {
              const joined = await imports.pathJoin({ base: absoluteBase, segment: value });
              return joined?.path || joined || value;
            } catch (_) {
              return value;
            }
          };
          const ragRoot = await resolvePath(ragRootCandidate, projectBase) || projectBase;

          const composePath = await resolvePath(
            'components/registry.register_helpers/compose.yaml',
            ragRoot
          );

          const helperRegistration = composePath
            ? [{ id: 'lcod://rag/registry/register_helpers@0.1.0', composePath }]
            : [];

          const snapshotPath = await resolvePath(
            ensureString(state.snapshotPath) ||
              await joinRelative(ragRoot, 'data/registry.snapshot.json'),
            projectBase
          );

          const cacheDir = await resolvePath(
            ensureString(state.cacheDir) ||
              await joinRelative(ragRoot, '.lcod/cache'),
            projectBase
          );

          const cataloguesUrl =
            ensureString(state.cataloguesUrl) ||
            'https://raw.githubusercontent.com/lcod-team/lcod-registry/main/catalogues.json';

          const cataloguesPath = await resolvePath(state.cataloguesPath, projectBase);
          const projectPath = await resolvePath(state.projectPath, '.');
          const cwd = await resolvePath(state.cwd, '.');

          return {
            helperRegistration,
            effectiveRagRoot: ragRoot,
            effectiveSnapshotPath: snapshotPath,
            effectiveCacheDir: cacheDir,
            effectiveCataloguesUrl: cataloguesUrl,
            effectiveCataloguesPath: cataloguesPath,
            effectiveProjectPath: projectPath,
            effectiveCwd: cwd
          };
        }
      input:
        ragRoot: $.ragRoot
        projectPath: $.projectPath
        cwd: $.cwd
        snapshotPath: $.snapshotPath
        cacheDir: $.cacheDir
        cataloguesUrl: $.cataloguesUrl
        cataloguesPath: $.cataloguesPath
      imports:
        pathJoin: lcod://axiom/path/join@1
    out:
      helperRegistration: helperRegistration
      ragRootResolved: effectiveRagRoot
      snapshotPathResolved: effectiveSnapshotPath
      cacheDirResolved: effectiveCacheDir
      cataloguesUrlResolved: effectiveCataloguesUrl
      cataloguesPathResolved: effectiveCataloguesPath
      projectPathResolved: effectiveProjectPath
      cwdResolved: effectiveCwd

  - call: lcod://tooling/resolver/register@1
    in:
      components: $.helperRegistration
    out:
      helperRegistered: bootstrapRegistered
      helperRegisterWarnings: bootstrapWarnings

  - call: lcod://rag/registry/register_helpers@0.1.0
    in:
      ragRoot: $.ragRootResolved
    out:
      helperRegistered: registered
      helperWarnings: helperWarnings

  - call: lcod://rag/registry/snapshot_read@0.1.0
    in:
      path: $.snapshotPathResolved
      warningMessage: $.missingSnapshotWarning
    out:
      snapshot: previousSnapshot
      exists: previousExists
      warnings: readWarnings

  - call: lcod://rag/registry/collect_components@0.1.0
    in:
      projectPath: $.projectPathResolved
      cataloguesPath: $.cataloguesPathResolved
      cataloguesUrl: $.cataloguesUrlResolved
      sourceId: $.sourceId
      cacheDir: $.cacheDirResolved
      cwd: $.cwdResolved
      specRoot: $.specRoot
      ragRoot: $.ragRootResolved
      repoRoots: $.repoRoots
    out:
      components: components
      warnings: collectWarnings
      componentCount: componentCount
      cataloguesCount: cataloguesCount

  - call: lcod://rag/registry/snapshot_from_components@0.1.0
    in:
      components: $.components
    out:
      snapshot: currentSnapshot
      entries: snapshotEntries

  - call: lcod://rag/registry/diff_snapshots@0.1.0
    in:
      previous: $.previousSnapshot
      current: $.currentSnapshot
    out:
      added: added
      removed: removed
      updated: updated
      unchanged: unchanged

  - call: lcod://tooling/value/default_array@0.1.0
    in:
      value: $.readWarnings
    out:
      accumulatedWarnings: resolved

  - call: lcod://tooling/value/default_array@0.1.0
    in:
      value: $.collectWarnings
    out:
      collectWarningsList: resolved

  - call: lcod://tooling/value/default_array@0.1.0
    in:
      value: $.bootstrapWarnings
    out:
      bootstrapWarningsList: resolved

  - call: lcod://tooling/value/default_array@0.1.0
    in:
      value: $.helperWarnings
    out:
      helperWarningsList: resolved

  - call: lcod://tooling/array/append@0.1.0
    in:
      items: $.accumulatedWarnings
      values: $.collectWarningsList
    out:
      warnings: items

  - call: lcod://tooling/array/append@0.1.0
    in:
      items: $.warnings
      values: $.bootstrapWarningsList
    out:
      warnings: items

  - call: lcod://tooling/array/append@0.1.0
    in:
      items: $.warnings
      values: $.helperWarningsList
    out:
      warnings: items

  - call: lcod://rag/array/compact@0.1.0
    in:
      items: $.warnings
    out:
      warnings: values

  - call: lcod://impl/set@1
    in:
      components: $.components
      snapshot: $.currentSnapshot
      snapshotEntries: $.snapshotEntries
      diff:
        added: $.added
        removed: $.removed
        updated: $.updated
        unchanged: $.unchanged
      previousExists: $.previousExists
      warnings: $.warnings
      componentCount: $.componentCount
      cataloguesCount: $.cataloguesCount
      snapshotPath: $.snapshotPathResolved
      cacheDir: $.cacheDirResolved
    out:
      components: components
      snapshot: snapshot
      snapshotEntries: snapshotEntries
      diff: diff
      previousExists: previousExists
      warnings: warnings
      componentCount: componentCount
      cataloguesCount: cataloguesCount
      snapshotPath: snapshotPath
      cacheDir: cacheDir
