schemaVersion = "2.0"
id = "lcod://rag/registry/load_manifest_records@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Resolve a registry manifest from URL or disk and return its component records."

[palette]
category = "RAG"
icon = "mdi:file-tree"
tags = ["registry", "manifest", "rag"]

[docs]
readme = "README.md"

[[io.input]]
name = "metadata"
summary = "Catalogue metadata describing manifest locations and source repository."
required = false
schema = """
{
  "type": ["object", "null"],
  "additionalProperties": true
}
"""

[[io.input]]
name = "repoRoots"
summary = "Lookup table mapping repository URLs to local directories."
required = false
schema = """
{
  "type": ["object", "null"],
  "additionalProperties": { "type": "string" }
}
"""

[[io.input]]
name = "repoRoot"
summary = "Fallback repository root to resolve relative paths."
required = false
schema = """
{
  "type": ["string", "null"]
}
"""

[[io.input]]
name = "specRoot"
summary = "Local lcod-spec checkout used for helper resolution."
required = false
schema = """
{
  "type": ["string", "null"]
}
"""

[[io.input]]
name = "ragRoot"
summary = "Local lcod-rag checkout used for helper resolution."
required = false
schema = """
{
  "type": ["string", "null"]
}
"""

[[io.input]]
name = "projectPath"
summary = "Project directory considered when resolving relative paths."
required = false
schema = """
{
  "type": ["string", "null"]
}
"""

[[io.input]]
name = "manifestPath"
summary = "Relative or absolute path to the manifest file."
required = false
schema = """
{
  "type": ["string", "null"]
}
"""

[[io.input]]
name = "manifestUrl"
summary = "Remote URL to fetch the manifest from."
required = false
schema = """
{
  "type": ["string", "null"]
}
"""

[[io.output]]
name = "records"
summary = "Raw manifest records (array of objects)."
schema = """
{
  "type": "array",
  "items": { "type": "object" }
}
"""

[[io.output]]
name = "warnings"
summary = "Warnings emitted while fetching or parsing the manifest."
schema = """
{
  "type": "array",
  "items": { "type": "string" }
}
"""
