compose:
  - call: lcod://tooling/script@1
    in:
      source: |
        async ({ state }) => {
          const values = [];
          const items = Array.isArray(state.items) ? state.items : [];
          for (const entry of items) {
            if (Array.isArray(entry)) {
              for (const nested of entry) {
                values.push(nested);
              }
            } else if (entry !== undefined && entry !== null) {
              values.push(entry);
            }
          }
          return { values };
        }
      input:
        items: $.items
    out:
      values: values
