schemaVersion = "2.0"
id = "lcod://rag/array/flatten@0.1.0"
version = "0.1.0"
kind = "component"
summary = "Flatten an array one level deep."

[palette]
category = "RAG"
icon = "mdi:arrange-bring-forward"
tags = ["array", "flatten", "rag"]

[docs]
readme = "README.md"

[[io.input]]
name = "items"
summary = "Array that may contain nested arrays to flatten."
required = false
schema = """
{
  "type": ["array", "null"],
  "items": {}
}
"""

[[io.output]]
name = "values"
summary = "Flattened array with nested arrays expanded one level."
schema = """
{
  "type": "array",
  "items": {}
}
"""
