schemaVersion = "2.0"
id = "lcod://rag/workspace@0.1.0"
version = "0.1.0"
kind = "workspace-package"
summary = "Workspace package for LCOD RAG helpers."

[workspace]
componentsDir = "components"

[palette]
category = "RAG"
icon = "mdi:brain"
tags = ["rag", "registry", "documentation"]

[docs]
readme = "README.md"
