schemaVersion = "1.0"
id = "lcod://rag/workspace@0.1.0"
name = "rag"
namespace = "rag"
version = "0.1.0"
kind = "workspace-package"

[workspace]
[[workspace.components]]
id = "lcod://rag/jsonl/parse_objects@0.1.0"
path = "components/jsonl.parse_objects"

[[workspace.components]]
id = "lcod://rag/array/compact@0.1.0"
path = "components/array.compact"

[[workspace.components]]
id = "lcod://rag/array/flatten@0.1.0"
path = "components/array.flatten"

[[workspace.components]]
id = "lcod://rag/array/pluck@0.1.0"
path = "components/array.pluck"

[[workspace.components]]
id = "lcod://rag/registry/normalize_component@0.1.0"
path = "components/registry.normalize_component"

[[workspace.components]]
id = "lcod://rag/registry/collect_components@0.1.0"
path = "components/registry.collect_components"

[[workspace.components]]
id = "lcod://rag/registry/snapshot_from_components@0.1.0"
path = "components/registry.snapshot_from_components"

[[workspace.components]]
id = "lcod://rag/registry/diff_snapshots@0.1.0"
path = "components/registry.diff_snapshots"

[[workspace.components]]
id = "lcod://rag/registry/snapshot_read@0.1.0"
path = "components/registry.snapshot_read"

[[workspace.components]]
id = "lcod://rag/registry/snapshot_write@0.1.0"
path = "components/registry.snapshot_write"

[[workspace.components]]
id = "lcod://rag/registry/prepare_ingestion@0.1.0"
path = "components/registry.prepare_ingestion"
