name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-registry-ingestion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lcod-rag
        uses: actions/checkout@v4

      - name: Checkout lcod-spec
        uses: actions/checkout@v4
        with:
          repository: lcod-team/lcod-spec
          path: lcod-spec

      - name: Checkout lcod-registry
        uses: actions/checkout@v4
        with:
          repository: lcod-team/lcod-registry
          path: lcod-registry

      - name: Checkout lcod-kernel-rs
        uses: actions/checkout@v4
        with:
          repository: lcod-team/lcod-kernel-rs
          path: lcod-kernel-rs

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Prepare input file
        run: |
          INPUT_DIR="${GITHUB_WORKSPACE}/.ci"
          INPUT_PATH="${INPUT_DIR}/input.json"
          mkdir -p "${INPUT_DIR}"
          cat <<JSON > "${INPUT_PATH}"
          {
            "projectPath": "${GITHUB_WORKSPACE}",
            "cataloguesPath": "${GITHUB_WORKSPACE}/lcod-registry/catalogues.json",
            "specRoot": "${GITHUB_WORKSPACE}/lcod-spec",
            "ragRoot": "${GITHUB_WORKSPACE}",
            "snapshotPath": "${INPUT_DIR}/previous_snapshot.json"
          }
          JSON

      - name: Build run_compose (release)
        run: cargo build --release --bin run_compose
        working-directory: lcod-kernel-rs

      - name: Run registry prepare_ingestion compose
        env:
          LCOD_HOME: ${GITHUB_WORKSPACE}/lcod-kernel-rs/target/release
        run: |
          ./target/release/run_compose \
            --project ${GITHUB_WORKSPACE} \
            --compose ${GITHUB_WORKSPACE}/packages/rag/components/registry.prepare_ingestion/compose.yaml \
            --state ${GITHUB_WORKSPACE}/.ci/input.json
        working-directory: lcod-kernel-rs
