name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-registry-ingestion:
    runs-on: ubuntu-latest
    env:
      LCOD_RUN_VERSION: lcod-run-v0.1.12
    steps:
      - name: Checkout lcod-rag
        uses: actions/checkout@v4

      - name: Prepare input file
        run: |
          INPUT_DIR="${GITHUB_WORKSPACE}/.ci"
          INPUT_PATH="${INPUT_DIR}/input.json"
          mkdir -p "${INPUT_DIR}"
          cat <<JSON > "${INPUT_PATH}"
          {
            "snapshotPath": "${INPUT_DIR}/registry_snapshot.json",
            "missingSnapshotWarning": "CI bootstrap snapshot"
          }
          JSON

      - name: Download lcod-run ${{ env.LCOD_RUN_VERSION }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/lcod-run"
          gh release download "${LCOD_RUN_VERSION}" \
            --repo lcod-team/lcod-kernel-rs \
            --pattern "lcod-run-linux-x86_64.tar.gz" \
            --dir "${GITHUB_WORKSPACE}/lcod-run"
          tar -xzf "${GITHUB_WORKSPACE}/lcod-run/lcod-run-linux-x86_64.tar.gz" -C "${GITHUB_WORKSPACE}/lcod-run"
          chmod +x "${GITHUB_WORKSPACE}/lcod-run/lcod-run"

      - name: Run registry prepare_ingestion compose
        env:
          LCOD_LOG_LEVEL: info
        run: |
          "${GITHUB_WORKSPACE}/lcod-run/lcod-run" \
            --compose "${GITHUB_WORKSPACE}/packages/rag/components/registry.prepare_ingestion/compose.yaml" \
            --input "${GITHUB_WORKSPACE}/.ci/input.json"
